---
# BEGIN
server:
  port: 7070

spring:
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
# END

users:
  admins:
    - gjoinsey1@blogger.com
    - scrosi4@cam.ac.uk
    - brundle@cam.ac.uk
